name: 'lakehouse_bitcoin'
version: '1.0.0'
config-version: 2

profile: 'lakehouse_bitcoin'

model-paths: ["models"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lakehouse_bitcoin:
    silver:
      +materialized: table
    gold:
      +materialized: table
